server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./db
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration
    enabled: true
